from __future__ import annotations

import argparse


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="rna3d_local")
    subparsers = parser.add_subparsers(dest="command", required=True)

    tdb = subparsers.add_parser("build-template-db", help="Build strict template database")
    tdb.add_argument("--external-templates", required=True)
    tdb.add_argument("--out-dir", required=True)

    eidx = subparsers.add_parser("build-embedding-index", help="Build template embeddings and ANN index")
    eidx.add_argument("--template-index", required=True)
    eidx.add_argument("--out-dir", required=True)
    eidx.add_argument("--embedding-dim", type=int, default=384)
    eidx.add_argument("--encoder", choices=["ribonanzanet2", "mock"], default="ribonanzanet2")
    eidx.add_argument("--model-path", default=None)
    eidx.add_argument("--ann-engine", choices=["faiss_ivfpq", "none"], default="faiss_ivfpq")

    desc = subparsers.add_parser("infer-description-family", help="Infer target family from description with offline LLM")
    desc.add_argument("--targets", required=True)
    desc.add_argument("--out-dir", required=True)
    desc.add_argument("--backend", choices=["llama_cpp", "rules"], default="llama_cpp")
    desc.add_argument("--llm-model-path", default=None)
    desc.add_argument("--template-family-map", default=None)

    chem = subparsers.add_parser("prepare-chemical-features", help="Build DMS/2A3 chemical features")
    chem.add_argument("--quickstart", required=True)
    chem.add_argument("--out", required=True)

    pair = subparsers.add_parser("derive-pairings-from-chemical", help="Derive pairings (pair_prob) from chemical_features (p_paired)")
    pair.add_argument("--chemical-features", required=True)
    pair.add_argument("--out", required=True)

    folds = subparsers.add_parser("build-homology-folds", help="Build strict homology-aware CV folds")
    folds.add_argument("--train-targets", required=True)
    folds.add_argument("--pdb-sequences", required=True)
    folds.add_argument("--train-labels", default=None, help="Required when backend=usalign_tm (ground-truth coordinates for train)")
    folds.add_argument("--out-dir", required=True)
    folds.add_argument("--backend", choices=["mmseqs2", "cdhit_est", "python", "usalign_tm"], default="mmseqs2")
    folds.add_argument("--identity-threshold", type=float, default=0.40)
    folds.add_argument("--coverage-threshold", type=float, default=0.80)
    folds.add_argument("--usalign-bin", default="src/rna3d_local/evaluation/USalign", help="Used when backend=usalign_tm")
    folds.add_argument("--tm-threshold", type=float, default=0.50, help="Cluster train targets when TM-score >= threshold (backend=usalign_tm)")
    folds.add_argument("--usalign-timeout-seconds", type=int, default=60, help="Timeout per USalign call (backend=usalign_tm)")
    folds.add_argument("--n-folds", type=int, default=5)
    folds.add_argument("--chain-separator", default="|")
    folds.add_argument("--mmseqs-bin", default="mmseqs")
    folds.add_argument("--cdhit-bin", default="cd-hit-est")
    folds.add_argument("--domain-labels", default=None)
    folds.add_argument("--domain-column", default="domain_label")
    folds.add_argument("--description-column", default="description")
    folds.add_argument("--allow-no-domain-stratification", action="store_true")

    fold_eval = subparsers.add_parser("evaluate-homology-folds", help="Evaluate homology folds prioritizing orphan metrics")
    fold_eval.add_argument("--train-folds", required=True)
    fold_eval.add_argument("--target-metrics", required=True)
    fold_eval.add_argument("--report", required=True)
    fold_eval.add_argument("--metric-column", default=None)
    fold_eval.add_argument("--orphan-labels", default=None)
    fold_eval.add_argument("--retrieval", default=None)
    fold_eval.add_argument("--retrieval-score-column", default=None)
    fold_eval.add_argument("--orphan-score-threshold", type=float, default=0.65)
    fold_eval.add_argument("--orphan-weight", type=float, default=0.70)

    ret = subparsers.add_parser("retrieve-templates-latent", help="Retrieve templates with latent embedding similarity")
    ret.add_argument("--template-index", required=True)
    ret.add_argument("--template-embeddings", required=True)
    ret.add_argument("--targets", required=True)
    ret.add_argument("--out", required=True)
    ret.add_argument("--top-k", type=int, default=64)
    ret.add_argument("--encoder", choices=["ribonanzanet2", "mock"], default="ribonanzanet2")
    ret.add_argument("--embedding-dim", type=int, default=384)
    ret.add_argument("--model-path", default=None)
    ret.add_argument("--ann-engine", choices=["faiss_ivfpq", "numpy_bruteforce"], default="faiss_ivfpq")
    ret.add_argument("--faiss-index", default=None)
    ret.add_argument("--family-prior", default=None)
    ret.add_argument("--weight-embed", type=float, default=0.70)
    ret.add_argument("--weight-llm", type=float, default=0.20)
    ret.add_argument("--weight-seq", type=float, default=0.10)

    tr = subparsers.add_parser("train-template-reranker", help="Train template reranker with chemical bias")
    tr.add_argument("--candidates", required=True)
    tr.add_argument("--chemical-features", required=True)
    tr.add_argument("--out-dir", required=True)
    tr.add_argument("--labels", default=None)
    tr.add_argument("--epochs", type=int, default=40)
    tr.add_argument("--learning-rate", type=float, default=1e-2)
    tr.add_argument("--seed", type=int, default=123)

    sr = subparsers.add_parser("score-template-reranker", help="Score and rerank template candidates")
    sr.add_argument("--candidates", required=True)
    sr.add_argument("--chemical-features", required=True)
    sr.add_argument("--model", required=True)
    sr.add_argument("--config", required=True)
    sr.add_argument("--out", required=True)
    sr.add_argument("--top-k", type=int, default=None)

    tbm = subparsers.add_parser("predict-tbm", help="Generate long TBM predictions")
    tbm.add_argument("--retrieval", required=True)
    tbm.add_argument("--templates", required=True)
    tbm.add_argument("--targets", required=True)
    tbm.add_argument("--out", required=True)
    tbm.add_argument("--n-models", type=int, default=5)

    ex = subparsers.add_parser("export-submission", help="Export strict submission CSV from long predictions")
    ex.add_argument("--sample", required=True)
    ex.add_argument("--predictions", required=True)
    ex.add_argument("--out", required=True)

    chk = subparsers.add_parser("check-submission", help="Strictly validate submission against sample")
    chk.add_argument("--sample", required=True)
    chk.add_argument("--submission", required=True)

    local_score = subparsers.add_parser("score-local-bestof5", help="Compute strict local Best-of-5 TM-score with USalign")
    local_score.add_argument("--ground-truth", required=True)
    local_score.add_argument("--submission", required=True)
    local_score.add_argument("--usalign-bin", required=True)
    local_score.add_argument("--timeout-seconds", type=int, default=900)
    local_score.add_argument("--ground-truth-mode", choices=["single", "best_of_gt_copies"], default="single")
    local_score.add_argument("--score-json", required=True)
    local_score.add_argument("--report", default=None)

    kaggle_score = subparsers.add_parser("score-local-kaggle-official", help="Score using official Kaggle metric.py (no fallback)")
    kaggle_score.add_argument("--ground-truth", required=True)
    kaggle_score.add_argument("--submission", required=True)
    kaggle_score.add_argument("--score-json", required=True)
    kaggle_score.add_argument("--report", required=True)
    kaggle_score.add_argument("--metric-py", default=None)

    sub = subparsers.add_parser("submit-kaggle-notebook", help="Submit notebook-only after strict local checks")
    sub.add_argument("--competition", required=True)
    sub.add_argument("--notebook-ref", required=True)
    sub.add_argument("--notebook-version", required=True)
    sub.add_argument("--notebook-file", default="submission.csv")
    sub.add_argument("--sample", required=True)
    sub.add_argument("--submission", required=True)
    sub.add_argument("--notebook-output-path", required=True)
    sub.add_argument("--score-json", required=True)
    sub.add_argument("--baseline-score", required=True, type=float)
    sub.add_argument("--message", required=True)
    sub.add_argument("--execute-submit", action="store_true")

    assets = subparsers.add_parser("build-phase2-assets", help="Validate and build phase2 offline assets manifest")
    assets.add_argument("--assets-dir", required=True)
    assets.add_argument("--manifest", default=None)

    fetch = subparsers.add_parser("fetch-pretrained-assets", help="Fetch pretrained/offline assets (weights) for Phase1/2")
    fetch.add_argument("--assets-dir", required=True)
    fetch.add_argument(
        "--include",
        action="append",
        choices=["ribonanzanet2", "ribonanzanet2_pairwise", "boltz1", "chai1", "rnapro"],
        required=True,
    )
    fetch.add_argument("--dry-run", action="store_true")
    fetch.add_argument("--timeout-seconds", type=int, default=60)
    fetch.add_argument("--max-bytes", type=int, default=None)

    sup = subparsers.add_parser(
        "prepare-rnapro-support-files",
        help="Prepare RNAPro support files (minimal CCD cache + empty templates.pt) for offline inference",
    )
    sup.add_argument("--model-dir", required=True)
    sup.add_argument("--codes", default="A,C,G,U")
    sup.add_argument("--components-url", default="https://files.wwpdb.org/pub/pdb/data/monomers/components.cif.gz")
    sup.add_argument("--timeout-seconds", type=int, default=10 * 60)
    sup.add_argument("--overwrite", action="store_true")

    cfg = subparsers.add_parser("write-phase2-model-configs", help="Write config.json entrypoints for phase2 offline model dirs")
    cfg.add_argument("--assets-dir", required=True)
    cfg.add_argument("--chain-separator", default="|")
    cfg.add_argument("--manifest", default=None)

    wh = subparsers.add_parser("build-wheelhouse", help="Build offline wheelhouse for Kaggle (download wheels)")
    wh.add_argument("--wheels-dir", required=True)
    wh.add_argument("--python-version", default="3.12")
    wh.add_argument("--platform", default="manylinux2014_x86_64")
    wh.add_argument("--profile", choices=["phase2"], default="phase2")
    wh.add_argument("--no-project-wheel", action="store_true")
    wh.add_argument("--timeout-seconds", type=int, default=60 * 60)
    wh.add_argument("--manifest", default=None)

    rna = subparsers.add_parser("predict-rnapro-offline", help="Run RNAPro offline inference")
    rna.add_argument("--model-dir", required=True)
    rna.add_argument("--targets", required=True)
    rna.add_argument("--out", required=True)
    rna.add_argument("--n-models", type=int, default=5)

    chai = subparsers.add_parser("predict-chai1-offline", help="Run Chai-1 offline single-sequence inference")
    chai.add_argument("--model-dir", required=True)
    chai.add_argument("--targets", required=True)
    chai.add_argument("--out", required=True)
    chai.add_argument("--n-models", type=int, default=5)

    boltz = subparsers.add_parser("predict-boltz1-offline", help="Run Boltz-1 offline multimodal inference")
    boltz.add_argument("--model-dir", required=True)
    boltz.add_argument("--targets", required=True)
    boltz.add_argument("--out", required=True)
    boltz.add_argument("--n-models", type=int, default=5)

    lab = subparsers.add_parser("prepare-phase1-data-lab", help="Precompute thermo/MSA and package lazy training store (.zarr)")
    lab.add_argument("--targets", required=True)
    lab.add_argument("--pairings", required=True)
    lab.add_argument("--chemical-features", required=True)
    lab.add_argument("--labels", required=True)
    lab.add_argument("--out-dir", required=True)
    lab.add_argument("--thermo-backend", choices=["rnafold", "linearfold", "viennarna"], default="rnafold")
    lab.add_argument("--rnafold-bin", default="RNAfold")
    lab.add_argument("--linearfold-bin", default="linearfold")
    lab.add_argument("--msa-backend", choices=["mmseqs2"], default="mmseqs2")
    lab.add_argument("--mmseqs-bin", default="mmseqs")
    lab.add_argument("--mmseqs-db", default="")
    lab.add_argument("--chain-separator", default="|")
    lab.add_argument("--max-msa-sequences", type=int, default=96)
    lab.add_argument("--max-cov-positions", type=int, default=256)
    lab.add_argument("--max-cov-pairs", type=int, default=8192)
    lab.add_argument("--workers", type=int, default=16)

    train_se3 = subparsers.add_parser("train-se3-generator", help="Train SE(3) generative branch (EGNN+IPA+Diffusion/Flow)")
    train_se3.add_argument("--targets", required=True)
    train_se3.add_argument("--pairings", required=True)
    train_se3.add_argument("--chemical-features", required=True)
    train_se3.add_argument("--labels", required=True)
    train_se3.add_argument("--config", required=True)
    train_se3.add_argument("--out-dir", required=True)
    train_se3.add_argument("--seed", type=int, default=123)
    train_se3.add_argument("--training-store", default=None, help="Path to precomputed training_store.zarr (lazy loading)")

    sample_se3 = subparsers.add_parser("sample-se3-ensemble", help="Sample SE(3) ensemble candidates")
    sample_se3.add_argument("--model-dir", required=True)
    sample_se3.add_argument("--targets", required=True)
    sample_se3.add_argument("--pairings", required=True)
    sample_se3.add_argument("--chemical-features", required=True)
    sample_se3.add_argument("--out", required=True)
    sample_se3.add_argument("--method", choices=["diffusion", "flow", "both"], default="both")
    sample_se3.add_argument("--n-samples", type=int, default=24)
    sample_se3.add_argument("--seed", type=int, default=123)

    rank_se3 = subparsers.add_parser("rank-se3-ensemble", help="Rank SE(3) ensemble by QA + diversity")
    rank_se3.add_argument("--candidates", required=True)
    rank_se3.add_argument("--out", required=True)
    rank_se3.add_argument("--qa-config", default=None)
    rank_se3.add_argument("--chemical-features", default=None)
    rank_se3.add_argument("--diversity-lambda", type=float, default=0.35)

    top5_se3 = subparsers.add_parser("select-top5-se3", help="Select diverse Top-5 from ranked SE(3) ensemble")
    top5_se3.add_argument("--ranked", required=True)
    top5_se3.add_argument("--out", required=True)
    top5_se3.add_argument("--n-models", type=int, default=5)
    top5_se3.add_argument("--diversity-lambda", type=float, default=0.35)

    router = subparsers.add_parser("build-hybrid-candidates", help="Build hybrid routed candidate pool")
    router.add_argument("--targets", required=True)
    router.add_argument("--retrieval", required=True)
    router.add_argument("--tbm", required=True)
    router.add_argument("--out", required=True)
    router.add_argument("--routing-out", required=True)
    router.add_argument("--template-score-threshold", type=float, default=0.65)
    router.add_argument("--ultra-long-seq-threshold", type=int, default=1500)
    router.add_argument("--rnapro", default=None)
    router.add_argument("--chai1", default=None)
    router.add_argument("--boltz1", default=None)
    router.add_argument("--se3", default=None)

    top5 = subparsers.add_parser("select-top5-hybrid", help="Select Top-5 models per target from hybrid candidates")
    top5.add_argument("--candidates", required=True)
    top5.add_argument("--out", required=True)
    top5.add_argument("--n-models", type=int, default=5)
    top5.add_argument("--diversity-lambda", type=float, default=0.35)

    mini = subparsers.add_parser("minimize-ensemble", help="Run post-inference geometric minimization on long predictions")
    mini.add_argument("--predictions", required=True)
    mini.add_argument("--out", required=True)
    mini.add_argument("--backend", choices=["openmm", "pyrosetta"], default="openmm")
    mini.add_argument("--max-iterations", type=int, default=80, help="0 desativa minimizacao; faixa valida: 0..100")
    mini.add_argument("--bond-length-angstrom", type=float, default=5.9)
    mini.add_argument("--bond-force-k", type=float, default=60.0)
    mini.add_argument("--angle-force-k", type=float, default=8.0)
    mini.add_argument("--angle-target-deg", type=float, default=120.0)
    mini.add_argument("--vdw-min-distance-angstrom", type=float, default=2.1)
    mini.add_argument("--vdw-epsilon", type=float, default=0.20)
    mini.add_argument("--position-restraint-k", type=float, default=800.0)
    mini.add_argument("--openmm-platform", default=None)

    ready = subparsers.add_parser("evaluate-submit-readiness", help="Evaluate strict submit readiness gate")
    ready.add_argument("--sample", required=True)
    ready.add_argument("--submission", required=True)
    ready.add_argument("--score-json", required=True)
    ready.add_argument("--baseline-score", required=True, type=float)
    ready.add_argument("--report", required=True)
    ready.add_argument("--allow-disallow", action="store_true", help="Do not fail when gate is disallowed")

    exp = subparsers.add_parser("run-experiment", help="Run reproducible experiment recipe (strict, fail-fast)")
    exp.add_argument("--recipe", required=True, help="Path to experiment recipe JSON")
    exp.add_argument("--runs-dir", default="runs", help="Base output directory for runs/")
    exp.add_argument("--tag", default=None, help="Override recipe tag for run directory naming")
    exp.add_argument(
        "--var",
        action="append",
        default=[],
        help="Override recipe variable (KEY=VALUE). Can be repeated.",
    )
    exp.add_argument("--dry-run", action="store_true", help="Validate and print expanded commands without executing")

    return parser
